apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-deployment
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo-deployment

# kubectl expose deployment mongo-deployment --name=mongo-service --type=ClusterIP --port=27017 --dry-run=client -o yaml > k8s-mongo-service.yaml


# kubectl expose deployment emp-deployment --name=emp-lb-service --type=LoadBalancer --port=8080 --dry-run=client -o yaml > k8s-emp-lb-service.yaml